pkgname=mate-system-tools

post_install() {
    usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas

    gtk-update-icon-cache -q -t -f usr/share/icons/mate

    update-desktop-database -q
}

post_upgrade() {
    post_install $1
}

post_remove() {
    usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
    gtk-update-icon-cache -q -t -f usr/share/icons/mate
    update-desktop-database -q
}
